apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::743680868500:role/dev-iwt-external-secrets-role" 