replicaCount: 1

image:
  repository: ghcr.io/danyapilovets/producer
  tag: "1.0.0"
  pullPolicy: Always

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 150m
    memory: 192Mi

service:
  type: ClusterIP
  port: 8001

kafka:
  bootstrapServers: kafka:9092
  topic: events.taxonomy

postgres:
  host: postgres
  port: 5432
