apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-serviceaccount
  namespace: dev
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::743680868500:role/dev-iwt-airflow-etl-role"
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-s3-connection
  namespace: dev
  labels:
    airflow-database: airflow
type: Opaque
stringData:
  AIRFLOW_CONN_S3_DATA: "s3://?region_name=eu-central-1&aws_iam_role=arn:aws:iam::743680868500:role/dev-iwt-airflow-etl-role"
  AIRFLOW_CONN_POSTGRES_DATA: "postgres://postgres:5432/banking_etl"