apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: apps/.helm/airflow/.charts/airflow-0.0.2.tgz
      sourceRef:
        kind: GitRepository
        name: dev-repo
        namespace: flux-system
  values:
    executor: "LocalExecutor"
    postgresql:
      enabled: false
    redis:
      enabled: false
    serviceAccount:
      create: false
      name: "airflow-serviceaccount"
