TRUNCATE TABLE fraud_alerts CASCADE;
TRUNCATE TABLE daily_transaction_summary CASCADE;
TRUNCATE TABLE transactions CASCADE;
TRUNCATE TABLE fraud_rules CASCADE;
TRUNCATE TABLE accounts CASCADE;
TRUNCATE TABLE customers CASCADE;
