TRUNCATE TABLE order_status;
TRUNCATE TABLE product CASCADE;
TRUNCATE TABLE country CASCADE;
TRUNCATE TABLE city CASCADE;
TRUNCATE TABLE store CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE status_name CASCADE;
TRUNCATE TABLE sale CASCADE;
TRUNCATE TABLE order_status_stats CASCADE;
