apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-consumer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-consumer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kafka-consumer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kafka-consumer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: kafka-consumer-sa
      containers:
      - name: consumer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          # AWS region and S3 bucket (IAM роль используется автоматически)
          - name: AWS_REGION
            value: "{{ .Values.awsRegion }}"
          - name: S3_BUCKET
            value: "{{ .Values.s3Bucket }}"
          # Kafka configuration
          - name: BOOTSTRAP_SERVERS
            value: {{ .Values.kafka.bootstrapServers }}
          - name: KAFKA_TOPIC
            value: {{ .Values.kafka.topic }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }} 