apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-consumer
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: apps/.helm/kafka-consumer/.charts/kafka-consumer-0.0.2.tgz
      sourceRef:
        kind: GitRepository
        name: dev-repo
        namespace: flux-system
  values:
    replicaCount: 1
    resources:
      limits:
        memory: 512Mi
        cpu: 300m
      requests:
        memory: 256Mi
        cpu: 150m

    s3Bucket: dev-iwt-private-2cap2d
    awsRegion: eu-central-1

    kafka:
      bootstrapServers: kafka:9092
      topic: card_tx
      consumerGroup: card-tx-s3-writer
    batchSize: 100
    flushIntervalSeconds: 30
