apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-postgres-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: postgres-secret
    creationPolicy: Merge
  dataFrom:
  - extract:
      key: dev-iwt-postgres-creds
  data:
  - secretKey: AIRFLOW_DB_CONN
    remoteRef:
      key: dev-iwt-postgres-creds
      property: connection_string
  template:
    type: Opaque
    data:
      AIRFLOW_DB_CONN: |
        postgresql+psycopg2://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@{{ .host }}:5432/{{ .POSTGRES_DB }} 