apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: QUtJQTIySldWUUNLR0lUWlVJNUg=
  AWS_DEFAULT_REGION: ZXUtY2VudHJhbC0x
  AWS_SECRET_ACCESS_KEY: ODFiVENzRC9QaDc5dGNuZXNLK1F1MEFwbVN6VWhoRDdUMXVNY2dFSg==
kind: Secret
metadata:
  name: aws-credentials
  namespace: dev
type: Opaque