apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: dev
type: Opaque
stringData:
  access_key_id: "${TERRAFORM_DEV_ACCESS_KEY}"
  secret_access_key: "${TERRAFORM_DEV_SECRET_KEY}" 