apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: airflow-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev-iwt-airflow-creds
