apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: dev
type: Opaque
stringData:
  # Используем terraform-dev профиль credentials
  # Получите их командой: aws configure get aws_access_key_id --profile terraform-dev
  access_key_id: "${TERRAFORM_DEV_ACCESS_KEY}"
  secret_access_key: "${TERRAFORM_DEV_SECRET_KEY}" 