apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      # Используем IRSA (IAM Roles for Service Accounts) для production
      # Для dev - secretRef с минимальными правами
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            namespace: dev  
            key: access_key_id
          secretAccessKeySecretRef:
            name: aws-credentials
            namespace: dev
            key: secret_access_key
