---
# Секрет для Kafka Consumer с S3 настройками
apiVersion: v1
kind: Secret
metadata:
  name: aws-consumer-secret
  namespace: dev
type: Opaque
stringData:
  # S3 настройки для Consumer
  aws_access_key_id: "AKIAIOSFODNN7EXAMPLE"     # Замените на реальные
  aws_secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"  # Замените на реальные
  aws_region: "eu-central-1"
  s3_bucket: "dev-iwt-private-bucket"
  s3_prefix: "landing/card_tx/"

---
# Секрет для Airflow с настройками БД и S3
apiVersion: v1
kind: Secret
metadata:
  name: aws-airflow-secret  
  namespace: dev
type: Opaque
stringData:
  # Airflow основные настройки
  airflow_admin_user: "admin"
  airflow_admin_password: "admin123"
  airflow_admin_email: "admin@bank.local"
  
  # S3 доступ для Airflow
  aws_access_key_id: "AKIAIOSFODNN7EXAMPLE"
  aws_secret_access_key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  aws_region: "eu-central-1"
  s3_bucket: "dev-iwt-private-bucket"
  
  # Fernet key для шифрования Airflow
  fernet_key: "zp8Q4K-bd0eBXaMqt3Y_jzEDnk2P1d8Lq7mF6nZjvhE="

---
# Секрет для Producer с Kafka настройками
apiVersion: v1
kind: Secret
metadata:
  name: producer-secret
  namespace: dev
type: Opaque
stringData:
  # Kafka настройки
  kafka_bootstrap_servers: "kafka:9092"
  kafka_topic: "card_tx"
  
  # Настройки генерации банковских транзакций
  batch_size: "10"
  interval_seconds: "5"
  
  # Список стран для генерации
  countries: "US,UK,DE,FR,RU,CA,AU"
  currencies: "USD,EUR,GBP,RUB" 