apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: producer
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: apps/.helm/producer
      sourceRef:
        kind: GitRepository
        name: dev-repo
        namespace: flux-system
  values:
    replicaCount: 1
    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 128Mi
        cpu: 100m
    kafka:
      bootstrapServers: kafka:9092
      topic: card_tx
    app:
      intervalSeconds: 5
      batchSize: 10
