apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: producer
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: apps/.helm/producer/.charts/producer-0.0.1.tgz
      sourceRef:
        kind: GitRepository
        name: dev-repo
        namespace: flux-system
  values:
    # МИНИМАЛЬНЫЕ РЕСУРСЫ ДЛЯ PRODUCER
    replicaCount: 1
    
    resources:
      limits:
        memory: 256Mi
        cpu: 200m
      requests:
        memory: 128Mi
        cpu: 100m
    
    kafka:
      bootstrapServers: kafka:9092
      topic: card_tx
    
    # Настройки для банковских транзакций
    app:
      intervalSeconds: 5  # Генерировать каждые 5 секунд
      batchSize: 10       # По 10 транзакций за раз
